/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: systrace.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "systrace.pb-c.h"
void   systrace__hook__stack_frame__init
                     (Systrace__Hook__StackFrame         *message)
{
  static const Systrace__Hook__StackFrame init_value = SYSTRACE__HOOK__STACK_FRAME__INIT;
  *message = init_value;
}
size_t systrace__hook__stack_frame__get_packed_size
                     (const Systrace__Hook__StackFrame *message)
{
  assert(message->base.descriptor == &systrace__hook__stack_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t systrace__hook__stack_frame__pack
                     (const Systrace__Hook__StackFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &systrace__hook__stack_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t systrace__hook__stack_frame__pack_to_buffer
                     (const Systrace__Hook__StackFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &systrace__hook__stack_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Systrace__Hook__StackFrame *
       systrace__hook__stack_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Systrace__Hook__StackFrame *)
     protobuf_c_message_unpack (&systrace__hook__stack_frame__descriptor,
                                allocator, len, data);
}
void   systrace__hook__stack_frame__free_unpacked
                     (Systrace__Hook__StackFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &systrace__hook__stack_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   systrace__hook__mem_alloc_entry__init
                     (Systrace__Hook__MemAllocEntry         *message)
{
  static const Systrace__Hook__MemAllocEntry init_value = SYSTRACE__HOOK__MEM_ALLOC_ENTRY__INIT;
  *message = init_value;
}
size_t systrace__hook__mem_alloc_entry__get_packed_size
                     (const Systrace__Hook__MemAllocEntry *message)
{
  assert(message->base.descriptor == &systrace__hook__mem_alloc_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t systrace__hook__mem_alloc_entry__pack
                     (const Systrace__Hook__MemAllocEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &systrace__hook__mem_alloc_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t systrace__hook__mem_alloc_entry__pack_to_buffer
                     (const Systrace__Hook__MemAllocEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &systrace__hook__mem_alloc_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Systrace__Hook__MemAllocEntry *
       systrace__hook__mem_alloc_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Systrace__Hook__MemAllocEntry *)
     protobuf_c_message_unpack (&systrace__hook__mem_alloc_entry__descriptor,
                                allocator, len, data);
}
void   systrace__hook__mem_alloc_entry__free_unpacked
                     (Systrace__Hook__MemAllocEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &systrace__hook__mem_alloc_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   systrace__hook__mem_free_entry__init
                     (Systrace__Hook__MemFreeEntry         *message)
{
  static const Systrace__Hook__MemFreeEntry init_value = SYSTRACE__HOOK__MEM_FREE_ENTRY__INIT;
  *message = init_value;
}
size_t systrace__hook__mem_free_entry__get_packed_size
                     (const Systrace__Hook__MemFreeEntry *message)
{
  assert(message->base.descriptor == &systrace__hook__mem_free_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t systrace__hook__mem_free_entry__pack
                     (const Systrace__Hook__MemFreeEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &systrace__hook__mem_free_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t systrace__hook__mem_free_entry__pack_to_buffer
                     (const Systrace__Hook__MemFreeEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &systrace__hook__mem_free_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Systrace__Hook__MemFreeEntry *
       systrace__hook__mem_free_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Systrace__Hook__MemFreeEntry *)
     protobuf_c_message_unpack (&systrace__hook__mem_free_entry__descriptor,
                                allocator, len, data);
}
void   systrace__hook__mem_free_entry__free_unpacked
                     (Systrace__Hook__MemFreeEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &systrace__hook__mem_free_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   systrace__hook__proc_mem__init
                     (Systrace__Hook__ProcMem         *message)
{
  static const Systrace__Hook__ProcMem init_value = SYSTRACE__HOOK__PROC_MEM__INIT;
  *message = init_value;
}
size_t systrace__hook__proc_mem__get_packed_size
                     (const Systrace__Hook__ProcMem *message)
{
  assert(message->base.descriptor == &systrace__hook__proc_mem__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t systrace__hook__proc_mem__pack
                     (const Systrace__Hook__ProcMem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &systrace__hook__proc_mem__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t systrace__hook__proc_mem__pack_to_buffer
                     (const Systrace__Hook__ProcMem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &systrace__hook__proc_mem__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Systrace__Hook__ProcMem *
       systrace__hook__proc_mem__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Systrace__Hook__ProcMem *)
     protobuf_c_message_unpack (&systrace__hook__proc_mem__descriptor,
                                allocator, len, data);
}
void   systrace__hook__proc_mem__free_unpacked
                     (Systrace__Hook__ProcMem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &systrace__hook__proc_mem__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   systrace__hook__gc_debug_data__init
                     (Systrace__Hook__GcDebugData         *message)
{
  static const Systrace__Hook__GcDebugData init_value = SYSTRACE__HOOK__GC_DEBUG_DATA__INIT;
  *message = init_value;
}
size_t systrace__hook__gc_debug_data__get_packed_size
                     (const Systrace__Hook__GcDebugData *message)
{
  assert(message->base.descriptor == &systrace__hook__gc_debug_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t systrace__hook__gc_debug_data__pack
                     (const Systrace__Hook__GcDebugData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &systrace__hook__gc_debug_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t systrace__hook__gc_debug_data__pack_to_buffer
                     (const Systrace__Hook__GcDebugData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &systrace__hook__gc_debug_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Systrace__Hook__GcDebugData *
       systrace__hook__gc_debug_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Systrace__Hook__GcDebugData *)
     protobuf_c_message_unpack (&systrace__hook__gc_debug_data__descriptor,
                                allocator, len, data);
}
void   systrace__hook__gc_debug_data__free_unpacked
                     (Systrace__Hook__GcDebugData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &systrace__hook__gc_debug_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   systrace__hook__pytorch_stage__init
                     (Systrace__Hook__PytorchStage         *message)
{
  static const Systrace__Hook__PytorchStage init_value = SYSTRACE__HOOK__PYTORCH_STAGE__INIT;
  *message = init_value;
}
size_t systrace__hook__pytorch_stage__get_packed_size
                     (const Systrace__Hook__PytorchStage *message)
{
  assert(message->base.descriptor == &systrace__hook__pytorch_stage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t systrace__hook__pytorch_stage__pack
                     (const Systrace__Hook__PytorchStage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &systrace__hook__pytorch_stage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t systrace__hook__pytorch_stage__pack_to_buffer
                     (const Systrace__Hook__PytorchStage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &systrace__hook__pytorch_stage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Systrace__Hook__PytorchStage *
       systrace__hook__pytorch_stage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Systrace__Hook__PytorchStage *)
     protobuf_c_message_unpack (&systrace__hook__pytorch_stage__descriptor,
                                allocator, len, data);
}
void   systrace__hook__pytorch_stage__free_unpacked
                     (Systrace__Hook__PytorchStage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &systrace__hook__pytorch_stage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   systrace__hook__pytorch__init
                     (Systrace__Hook__Pytorch         *message)
{
  static const Systrace__Hook__Pytorch init_value = SYSTRACE__HOOK__PYTORCH__INIT;
  *message = init_value;
}
size_t systrace__hook__pytorch__get_packed_size
                     (const Systrace__Hook__Pytorch *message)
{
  assert(message->base.descriptor == &systrace__hook__pytorch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t systrace__hook__pytorch__pack
                     (const Systrace__Hook__Pytorch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &systrace__hook__pytorch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t systrace__hook__pytorch__pack_to_buffer
                     (const Systrace__Hook__Pytorch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &systrace__hook__pytorch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Systrace__Hook__Pytorch *
       systrace__hook__pytorch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Systrace__Hook__Pytorch *)
     protobuf_c_message_unpack (&systrace__hook__pytorch__descriptor,
                                allocator, len, data);
}
void   systrace__hook__pytorch__free_unpacked
                     (Systrace__Hook__Pytorch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &systrace__hook__pytorch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   systrace__hook__mem__init
                     (Systrace__Hook__Mem         *message)
{
  static const Systrace__Hook__Mem init_value = SYSTRACE__HOOK__MEM__INIT;
  *message = init_value;
}
size_t systrace__hook__mem__get_packed_size
                     (const Systrace__Hook__Mem *message)
{
  assert(message->base.descriptor == &systrace__hook__mem__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t systrace__hook__mem__pack
                     (const Systrace__Hook__Mem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &systrace__hook__mem__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t systrace__hook__mem__pack_to_buffer
                     (const Systrace__Hook__Mem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &systrace__hook__mem__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Systrace__Hook__Mem *
       systrace__hook__mem__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Systrace__Hook__Mem *)
     protobuf_c_message_unpack (&systrace__hook__mem__descriptor,
                                allocator, len, data);
}
void   systrace__hook__mem__free_unpacked
                     (Systrace__Hook__Mem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &systrace__hook__mem__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor systrace__hook__stack_frame__field_descriptors[2] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__StackFrame, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "so_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__StackFrame, so_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned systrace__hook__stack_frame__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = so_name */
};
static const ProtobufCIntRange systrace__hook__stack_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor systrace__hook__stack_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "systrace.hook.StackFrame",
  "StackFrame",
  "Systrace__Hook__StackFrame",
  "systrace.hook",
  sizeof(Systrace__Hook__StackFrame),
  2,
  systrace__hook__stack_frame__field_descriptors,
  systrace__hook__stack_frame__field_indices_by_name,
  1,  systrace__hook__stack_frame__number_ranges,
  (ProtobufCMessageInit) systrace__hook__stack_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor systrace__hook__mem_alloc_entry__field_descriptors[5] =
{
  {
    "alloc_ptr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__MemAllocEntry, alloc_ptr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stage_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__MemAllocEntry, stage_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stage_type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__MemAllocEntry, stage_type),
    &systrace__hook__stage_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_size",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__MemAllocEntry, mem_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stack_frames",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Systrace__Hook__MemAllocEntry, n_stack_frames),
    offsetof(Systrace__Hook__MemAllocEntry, stack_frames),
    &systrace__hook__stack_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned systrace__hook__mem_alloc_entry__field_indices_by_name[] = {
  0,   /* field[0] = alloc_ptr */
  3,   /* field[3] = mem_size */
  4,   /* field[4] = stack_frames */
  1,   /* field[1] = stage_id */
  2,   /* field[2] = stage_type */
};
static const ProtobufCIntRange systrace__hook__mem_alloc_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor systrace__hook__mem_alloc_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "systrace.hook.MemAllocEntry",
  "MemAllocEntry",
  "Systrace__Hook__MemAllocEntry",
  "systrace.hook",
  sizeof(Systrace__Hook__MemAllocEntry),
  5,
  systrace__hook__mem_alloc_entry__field_descriptors,
  systrace__hook__mem_alloc_entry__field_indices_by_name,
  1,  systrace__hook__mem_alloc_entry__number_ranges,
  (ProtobufCMessageInit) systrace__hook__mem_alloc_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor systrace__hook__mem_free_entry__field_descriptors[1] =
{
  {
    "alloc_ptr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__MemFreeEntry, alloc_ptr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned systrace__hook__mem_free_entry__field_indices_by_name[] = {
  0,   /* field[0] = alloc_ptr */
};
static const ProtobufCIntRange systrace__hook__mem_free_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor systrace__hook__mem_free_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "systrace.hook.MemFreeEntry",
  "MemFreeEntry",
  "Systrace__Hook__MemFreeEntry",
  "systrace.hook",
  sizeof(Systrace__Hook__MemFreeEntry),
  1,
  systrace__hook__mem_free_entry__field_descriptors,
  systrace__hook__mem_free_entry__field_indices_by_name,
  1,  systrace__hook__mem_free_entry__number_ranges,
  (ProtobufCMessageInit) systrace__hook__mem_free_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor systrace__hook__proc_mem__field_descriptors[3] =
{
  {
    "pid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__ProcMem, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_alloc_stacks",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Systrace__Hook__ProcMem, n_mem_alloc_stacks),
    offsetof(Systrace__Hook__ProcMem, mem_alloc_stacks),
    &systrace__hook__mem_alloc_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_free_stacks",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Systrace__Hook__ProcMem, n_mem_free_stacks),
    offsetof(Systrace__Hook__ProcMem, mem_free_stacks),
    &systrace__hook__mem_free_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned systrace__hook__proc_mem__field_indices_by_name[] = {
  1,   /* field[1] = mem_alloc_stacks */
  2,   /* field[2] = mem_free_stacks */
  0,   /* field[0] = pid */
};
static const ProtobufCIntRange systrace__hook__proc_mem__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor systrace__hook__proc_mem__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "systrace.hook.ProcMem",
  "ProcMem",
  "Systrace__Hook__ProcMem",
  "systrace.hook",
  sizeof(Systrace__Hook__ProcMem),
  3,
  systrace__hook__proc_mem__field_descriptors,
  systrace__hook__proc_mem__field_indices_by_name,
  1,  systrace__hook__proc_mem__number_ranges,
  (ProtobufCMessageInit) systrace__hook__proc_mem__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor systrace__hook__gc_debug_data__field_descriptors[2] =
{
  {
    "collected",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__GcDebugData, collected),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uncollectable",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__GcDebugData, uncollectable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned systrace__hook__gc_debug_data__field_indices_by_name[] = {
  0,   /* field[0] = collected */
  1,   /* field[1] = uncollectable */
};
static const ProtobufCIntRange systrace__hook__gc_debug_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor systrace__hook__gc_debug_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "systrace.hook.GcDebugData",
  "GcDebugData",
  "Systrace__Hook__GcDebugData",
  "systrace.hook",
  sizeof(Systrace__Hook__GcDebugData),
  2,
  systrace__hook__gc_debug_data__field_descriptors,
  systrace__hook__gc_debug_data__field_indices_by_name,
  1,  systrace__hook__gc_debug_data__number_ranges,
  (ProtobufCMessageInit) systrace__hook__gc_debug_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor systrace__hook__pytorch_stage__field_descriptors[6] =
{
  {
    "stage_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__PytorchStage, stage_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stage_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__PytorchStage, stage_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_us",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__PytorchStage, start_us),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_us",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__PytorchStage, end_us),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stack_frames",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Systrace__Hook__PytorchStage, n_stack_frames),
    offsetof(Systrace__Hook__PytorchStage, stack_frames),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gc_debug",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Systrace__Hook__PytorchStage, debug_data_case),
    offsetof(Systrace__Hook__PytorchStage, gc_debug),
    &systrace__hook__gc_debug_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned systrace__hook__pytorch_stage__field_indices_by_name[] = {
  3,   /* field[3] = end_us */
  5,   /* field[5] = gc_debug */
  4,   /* field[4] = stack_frames */
  0,   /* field[0] = stage_id */
  1,   /* field[1] = stage_type */
  2,   /* field[2] = start_us */
};
static const ProtobufCIntRange systrace__hook__pytorch_stage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor systrace__hook__pytorch_stage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "systrace.hook.PytorchStage",
  "PytorchStage",
  "Systrace__Hook__PytorchStage",
  "systrace.hook",
  sizeof(Systrace__Hook__PytorchStage),
  6,
  systrace__hook__pytorch_stage__field_descriptors,
  systrace__hook__pytorch_stage__field_indices_by_name,
  1,  systrace__hook__pytorch_stage__number_ranges,
  (ProtobufCMessageInit) systrace__hook__pytorch_stage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor systrace__hook__pytorch__field_descriptors[4] =
{
  {
    "pytorch_stages",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Systrace__Hook__Pytorch, n_pytorch_stages),
    offsetof(Systrace__Hook__Pytorch, pytorch_stages),
    &systrace__hook__pytorch_stage__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rank",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__Pytorch, rank),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "step_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__Pytorch, step_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comm",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Systrace__Hook__Pytorch, comm),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned systrace__hook__pytorch__field_indices_by_name[] = {
  3,   /* field[3] = comm */
  0,   /* field[0] = pytorch_stages */
  1,   /* field[1] = rank */
  2,   /* field[2] = step_id */
};
static const ProtobufCIntRange systrace__hook__pytorch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor systrace__hook__pytorch__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "systrace.hook.Pytorch",
  "Pytorch",
  "Systrace__Hook__Pytorch",
  "systrace.hook",
  sizeof(Systrace__Hook__Pytorch),
  4,
  systrace__hook__pytorch__field_descriptors,
  systrace__hook__pytorch__field_indices_by_name,
  1,  systrace__hook__pytorch__number_ranges,
  (ProtobufCMessageInit) systrace__hook__pytorch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor systrace__hook__mem__field_descriptors[1] =
{
  {
    "proc_mem",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Systrace__Hook__Mem, n_proc_mem),
    offsetof(Systrace__Hook__Mem, proc_mem),
    &systrace__hook__proc_mem__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned systrace__hook__mem__field_indices_by_name[] = {
  0,   /* field[0] = proc_mem */
};
static const ProtobufCIntRange systrace__hook__mem__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor systrace__hook__mem__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "systrace.hook.Mem",
  "Mem",
  "Systrace__Hook__Mem",
  "systrace.hook",
  sizeof(Systrace__Hook__Mem),
  1,
  systrace__hook__mem__field_descriptors,
  systrace__hook__mem__field_indices_by_name,
  1,  systrace__hook__mem__number_ranges,
  (ProtobufCMessageInit) systrace__hook__mem__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue systrace__hook__stage_type__enum_values_by_number[3] =
{
  { "STAGE_DATALOADER", "SYSTRACE__HOOK__STAGE_TYPE__STAGE_DATALOADER", 0 },
  { "STAGE_FORWARD", "SYSTRACE__HOOK__STAGE_TYPE__STAGE_FORWARD", 1 },
  { "STAGE_BACKWARD", "SYSTRACE__HOOK__STAGE_TYPE__STAGE_BACKWARD", 2 },
};
static const ProtobufCIntRange systrace__hook__stage_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex systrace__hook__stage_type__enum_values_by_name[3] =
{
  { "STAGE_BACKWARD", 2 },
  { "STAGE_DATALOADER", 0 },
  { "STAGE_FORWARD", 1 },
};
const ProtobufCEnumDescriptor systrace__hook__stage_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "systrace.hook.StageType",
  "StageType",
  "Systrace__Hook__StageType",
  "systrace.hook",
  3,
  systrace__hook__stage_type__enum_values_by_number,
  3,
  systrace__hook__stage_type__enum_values_by_name,
  1,
  systrace__hook__stage_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
