/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: systrace.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "systrace.pb-c.h"
void   stack_frame__init
                     (StackFrame         *message)
{
  static const StackFrame init_value = STACK_FRAME__INIT;
  *message = init_value;
}
size_t stack_frame__get_packed_size
                     (const StackFrame *message)
{
  assert(message->base.descriptor == &stack_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_frame__pack
                     (const StackFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_frame__pack_to_buffer
                     (const StackFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackFrame *
       stack_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackFrame *)
     protobuf_c_message_unpack (&stack_frame__descriptor,
                                allocator, len, data);
}
void   stack_frame__free_unpacked
                     (StackFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mem_alloc_entry__init
                     (MemAllocEntry         *message)
{
  static const MemAllocEntry init_value = MEM_ALLOC_ENTRY__INIT;
  *message = init_value;
}
size_t mem_alloc_entry__get_packed_size
                     (const MemAllocEntry *message)
{
  assert(message->base.descriptor == &mem_alloc_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mem_alloc_entry__pack
                     (const MemAllocEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mem_alloc_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mem_alloc_entry__pack_to_buffer
                     (const MemAllocEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mem_alloc_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MemAllocEntry *
       mem_alloc_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MemAllocEntry *)
     protobuf_c_message_unpack (&mem_alloc_entry__descriptor,
                                allocator, len, data);
}
void   mem_alloc_entry__free_unpacked
                     (MemAllocEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mem_alloc_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mem_free_entry__init
                     (MemFreeEntry         *message)
{
  static const MemFreeEntry init_value = MEM_FREE_ENTRY__INIT;
  *message = init_value;
}
size_t mem_free_entry__get_packed_size
                     (const MemFreeEntry *message)
{
  assert(message->base.descriptor == &mem_free_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mem_free_entry__pack
                     (const MemFreeEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mem_free_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mem_free_entry__pack_to_buffer
                     (const MemFreeEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mem_free_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MemFreeEntry *
       mem_free_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MemFreeEntry *)
     protobuf_c_message_unpack (&mem_free_entry__descriptor,
                                allocator, len, data);
}
void   mem_free_entry__free_unpacked
                     (MemFreeEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mem_free_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proc_mem__init
                     (ProcMem         *message)
{
  static const ProcMem init_value = PROC_MEM__INIT;
  *message = init_value;
}
size_t proc_mem__get_packed_size
                     (const ProcMem *message)
{
  assert(message->base.descriptor == &proc_mem__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proc_mem__pack
                     (const ProcMem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proc_mem__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proc_mem__pack_to_buffer
                     (const ProcMem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proc_mem__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProcMem *
       proc_mem__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProcMem *)
     protobuf_c_message_unpack (&proc_mem__descriptor,
                                allocator, len, data);
}
void   proc_mem__free_unpacked
                     (ProcMem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proc_mem__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gc_debug_data__init
                     (GcDebugData         *message)
{
  static const GcDebugData init_value = GC_DEBUG_DATA__INIT;
  *message = init_value;
}
size_t gc_debug_data__get_packed_size
                     (const GcDebugData *message)
{
  assert(message->base.descriptor == &gc_debug_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gc_debug_data__pack
                     (const GcDebugData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gc_debug_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gc_debug_data__pack_to_buffer
                     (const GcDebugData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gc_debug_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GcDebugData *
       gc_debug_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GcDebugData *)
     protobuf_c_message_unpack (&gc_debug_data__descriptor,
                                allocator, len, data);
}
void   gc_debug_data__free_unpacked
                     (GcDebugData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gc_debug_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pytorch_stage__init
                     (PytorchStage         *message)
{
  static const PytorchStage init_value = PYTORCH_STAGE__INIT;
  *message = init_value;
}
size_t pytorch_stage__get_packed_size
                     (const PytorchStage *message)
{
  assert(message->base.descriptor == &pytorch_stage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pytorch_stage__pack
                     (const PytorchStage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pytorch_stage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pytorch_stage__pack_to_buffer
                     (const PytorchStage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pytorch_stage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PytorchStage *
       pytorch_stage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PytorchStage *)
     protobuf_c_message_unpack (&pytorch_stage__descriptor,
                                allocator, len, data);
}
void   pytorch_stage__free_unpacked
                     (PytorchStage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pytorch_stage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pytorch__init
                     (Pytorch         *message)
{
  static const Pytorch init_value = PYTORCH__INIT;
  *message = init_value;
}
size_t pytorch__get_packed_size
                     (const Pytorch *message)
{
  assert(message->base.descriptor == &pytorch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pytorch__pack
                     (const Pytorch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pytorch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pytorch__pack_to_buffer
                     (const Pytorch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pytorch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pytorch *
       pytorch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pytorch *)
     protobuf_c_message_unpack (&pytorch__descriptor,
                                allocator, len, data);
}
void   pytorch__free_unpacked
                     (Pytorch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pytorch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mem__init
                     (Mem         *message)
{
  static const Mem init_value = MEM__INIT;
  *message = init_value;
}
size_t mem__get_packed_size
                     (const Mem *message)
{
  assert(message->base.descriptor == &mem__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mem__pack
                     (const Mem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mem__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mem__pack_to_buffer
                     (const Mem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mem__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mem *
       mem__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mem *)
     protobuf_c_message_unpack (&mem__descriptor,
                                allocator, len, data);
}
void   mem__free_unpacked
                     (Mem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mem__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor stack_frame__field_descriptors[2] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StackFrame, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "so_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StackFrame, so_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stack_frame__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = so_name */
};
static const ProtobufCIntRange stack_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor stack_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackFrame",
  "StackFrame",
  "StackFrame",
  "",
  sizeof(StackFrame),
  2,
  stack_frame__field_descriptors,
  stack_frame__field_indices_by_name,
  1,  stack_frame__number_ranges,
  (ProtobufCMessageInit) stack_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mem_alloc_entry__field_descriptors[5] =
{
  {
    "alloc_ptr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MemAllocEntry, alloc_ptr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stage_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MemAllocEntry, stage_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stage_type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MemAllocEntry, stage_type),
    &stage_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_size",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MemAllocEntry, mem_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stack_frames",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MemAllocEntry, n_stack_frames),
    offsetof(MemAllocEntry, stack_frames),
    &stack_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mem_alloc_entry__field_indices_by_name[] = {
  0,   /* field[0] = alloc_ptr */
  3,   /* field[3] = mem_size */
  4,   /* field[4] = stack_frames */
  1,   /* field[1] = stage_id */
  2,   /* field[2] = stage_type */
};
static const ProtobufCIntRange mem_alloc_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor mem_alloc_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MemAllocEntry",
  "MemAllocEntry",
  "MemAllocEntry",
  "",
  sizeof(MemAllocEntry),
  5,
  mem_alloc_entry__field_descriptors,
  mem_alloc_entry__field_indices_by_name,
  1,  mem_alloc_entry__number_ranges,
  (ProtobufCMessageInit) mem_alloc_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mem_free_entry__field_descriptors[1] =
{
  {
    "alloc_ptr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MemFreeEntry, alloc_ptr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mem_free_entry__field_indices_by_name[] = {
  0,   /* field[0] = alloc_ptr */
};
static const ProtobufCIntRange mem_free_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mem_free_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MemFreeEntry",
  "MemFreeEntry",
  "MemFreeEntry",
  "",
  sizeof(MemFreeEntry),
  1,
  mem_free_entry__field_descriptors,
  mem_free_entry__field_indices_by_name,
  1,  mem_free_entry__number_ranges,
  (ProtobufCMessageInit) mem_free_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proc_mem__field_descriptors[3] =
{
  {
    "pid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProcMem, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_alloc_stacks",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProcMem, n_mem_alloc_stacks),
    offsetof(ProcMem, mem_alloc_stacks),
    &mem_alloc_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_free_stacks",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProcMem, n_mem_free_stacks),
    offsetof(ProcMem, mem_free_stacks),
    &mem_free_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proc_mem__field_indices_by_name[] = {
  1,   /* field[1] = mem_alloc_stacks */
  2,   /* field[2] = mem_free_stacks */
  0,   /* field[0] = pid */
};
static const ProtobufCIntRange proc_mem__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proc_mem__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProcMem",
  "ProcMem",
  "ProcMem",
  "",
  sizeof(ProcMem),
  3,
  proc_mem__field_descriptors,
  proc_mem__field_indices_by_name,
  1,  proc_mem__number_ranges,
  (ProtobufCMessageInit) proc_mem__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gc_debug_data__field_descriptors[2] =
{
  {
    "collected",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GcDebugData, collected),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uncollectable",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GcDebugData, uncollectable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gc_debug_data__field_indices_by_name[] = {
  0,   /* field[0] = collected */
  1,   /* field[1] = uncollectable */
};
static const ProtobufCIntRange gc_debug_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gc_debug_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GcDebugData",
  "GcDebugData",
  "GcDebugData",
  "",
  sizeof(GcDebugData),
  2,
  gc_debug_data__field_descriptors,
  gc_debug_data__field_indices_by_name,
  1,  gc_debug_data__number_ranges,
  (ProtobufCMessageInit) gc_debug_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pytorch_stage__field_descriptors[6] =
{
  {
    "stage_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PytorchStage, stage_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stage_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PytorchStage, stage_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_us",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PytorchStage, start_us),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_us",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PytorchStage, end_us),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stack_frames",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(PytorchStage, n_stack_frames),
    offsetof(PytorchStage, stack_frames),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gc_debug",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PytorchStage, debug_data_case),
    offsetof(PytorchStage, gc_debug),
    &gc_debug_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pytorch_stage__field_indices_by_name[] = {
  3,   /* field[3] = end_us */
  5,   /* field[5] = gc_debug */
  4,   /* field[4] = stack_frames */
  0,   /* field[0] = stage_id */
  1,   /* field[1] = stage_type */
  2,   /* field[2] = start_us */
};
static const ProtobufCIntRange pytorch_stage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor pytorch_stage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PytorchStage",
  "PytorchStage",
  "PytorchStage",
  "",
  sizeof(PytorchStage),
  6,
  pytorch_stage__field_descriptors,
  pytorch_stage__field_indices_by_name,
  1,  pytorch_stage__number_ranges,
  (ProtobufCMessageInit) pytorch_stage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pytorch__field_descriptors[4] =
{
  {
    "pytorch_stages",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pytorch, n_pytorch_stages),
    offsetof(Pytorch, pytorch_stages),
    &pytorch_stage__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rank",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Pytorch, rank),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "step_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Pytorch, step_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comm",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pytorch, comm),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pytorch__field_indices_by_name[] = {
  3,   /* field[3] = comm */
  0,   /* field[0] = pytorch_stages */
  1,   /* field[1] = rank */
  2,   /* field[2] = step_id */
};
static const ProtobufCIntRange pytorch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pytorch__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Pytorch",
  "Pytorch",
  "Pytorch",
  "",
  sizeof(Pytorch),
  4,
  pytorch__field_descriptors,
  pytorch__field_indices_by_name,
  1,  pytorch__number_ranges,
  (ProtobufCMessageInit) pytorch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mem__field_descriptors[1] =
{
  {
    "proc_mem",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Mem, n_proc_mem),
    offsetof(Mem, proc_mem),
    &proc_mem__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mem__field_indices_by_name[] = {
  0,   /* field[0] = proc_mem */
};
static const ProtobufCIntRange mem__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mem__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Mem",
  "Mem",
  "Mem",
  "",
  sizeof(Mem),
  1,
  mem__field_descriptors,
  mem__field_indices_by_name,
  1,  mem__number_ranges,
  (ProtobufCMessageInit) mem__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue stage_type__enum_values_by_number[3] =
{
  { "STAGE_DATALOADER", "STAGE_TYPE__STAGE_DATALOADER", 0 },
  { "STAGE_FORWARD", "STAGE_TYPE__STAGE_FORWARD", 1 },
  { "STAGE_BACKWARD", "STAGE_TYPE__STAGE_BACKWARD", 2 },
};
static const ProtobufCIntRange stage_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex stage_type__enum_values_by_name[3] =
{
  { "STAGE_BACKWARD", 2 },
  { "STAGE_DATALOADER", 0 },
  { "STAGE_FORWARD", 1 },
};
const ProtobufCEnumDescriptor stage_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "StageType",
  "StageType",
  "StageType",
  "",
  3,
  stage_type__enum_values_by_number,
  3,
  stage_type__enum_values_by_name,
  1,
  stage_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
