/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: trace.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "trace.pb-c.h"
void   stack_frame__init
                     (StackFrame         *message)
{
  static const StackFrame init_value = STACK_FRAME__INIT;
  *message = init_value;
}
size_t stack_frame__get_packed_size
                     (const StackFrame *message)
{
  assert(message->base.descriptor == &stack_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_frame__pack
                     (const StackFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_frame__pack_to_buffer
                     (const StackFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackFrame *
       stack_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackFrame *)
     protobuf_c_message_unpack (&stack_frame__descriptor,
                                allocator, len, data);
}
void   stack_frame__free_unpacked
                     (StackFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   arguments__init
                     (Arguments         *message)
{
  static const Arguments init_value = ARGUMENTS__INIT;
  *message = init_value;
}
size_t arguments__get_packed_size
                     (const Arguments *message)
{
  assert(message->base.descriptor == &arguments__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t arguments__pack
                     (const Arguments *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &arguments__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t arguments__pack_to_buffer
                     (const Arguments *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &arguments__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Arguments *
       arguments__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Arguments *)
     protobuf_c_message_unpack (&arguments__descriptor,
                                allocator, len, data);
}
void   arguments__free_unpacked
                     (Arguments *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &arguments__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   event__init
                     (Event         *message)
{
  static const Event init_value = EVENT__INIT;
  *message = init_value;
}
size_t event__get_packed_size
                     (const Event *message)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t event__pack
                     (const Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t event__pack_to_buffer
                     (const Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Event *
       event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Event *)
     protobuf_c_message_unpack (&event__descriptor,
                                allocator, len, data);
}
void   event__free_unpacked
                     (Event *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trace_data__stack_frames_entry__init
                     (TraceData__StackFramesEntry         *message)
{
  static const TraceData__StackFramesEntry init_value = TRACE_DATA__STACK_FRAMES_ENTRY__INIT;
  *message = init_value;
}
void   trace_data__init
                     (TraceData         *message)
{
  static const TraceData init_value = TRACE_DATA__INIT;
  *message = init_value;
}
size_t trace_data__get_packed_size
                     (const TraceData *message)
{
  assert(message->base.descriptor == &trace_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trace_data__pack
                     (const TraceData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trace_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trace_data__pack_to_buffer
                     (const TraceData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trace_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TraceData *
       trace_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TraceData *)
     protobuf_c_message_unpack (&trace_data__descriptor,
                                allocator, len, data);
}
void   trace_data__free_unpacked
                     (TraceData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trace_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor stack_frame__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StackFrame, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StackFrame, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "category",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StackFrame, category),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StackFrame, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stack_frame__field_indices_by_name[] = {
  2,   /* field[2] = category */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  3,   /* field[3] = parent */
};
static const ProtobufCIntRange stack_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor stack_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackFrame",
  "StackFrame",
  "StackFrame",
  "",
  sizeof(StackFrame),
  4,
  stack_frame__field_descriptors,
  stack_frame__field_indices_by_name,
  1,  stack_frame__number_ranges,
  (ProtobufCMessageInit) stack_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor arguments__field_descriptors[4] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Arguments, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Arguments, thread_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "futex_top",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Arguments, n_futex_top),
    offsetof(Arguments, futex_top),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "event_type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Arguments, event_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned arguments__field_indices_by_name[] = {
  0,   /* field[0] = count */
  3,   /* field[3] = event_type */
  2,   /* field[2] = futex_top */
  1,   /* field[1] = thread_name */
};
static const ProtobufCIntRange arguments__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor arguments__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Arguments",
  "Arguments",
  "Arguments",
  "",
  sizeof(Arguments),
  4,
  arguments__field_descriptors,
  arguments__field_indices_by_name,
  1,  arguments__number_ranges,
  (ProtobufCMessageInit) arguments__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor event__field_descriptors[9] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Event, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cat",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Event, cat),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Event, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tid",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Event, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ts",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Event, ts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dur",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Event, dur),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "track",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Event, track),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "args",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Event, args),
    &arguments__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stack_frames",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Event, n_stack_frames),
    offsetof(Event, stack_frames),
    &stack_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned event__field_indices_by_name[] = {
  7,   /* field[7] = args */
  1,   /* field[1] = cat */
  5,   /* field[5] = dur */
  0,   /* field[0] = name */
  2,   /* field[2] = pid */
  8,   /* field[8] = stack_frames */
  3,   /* field[3] = tid */
  6,   /* field[6] = track */
  4,   /* field[4] = ts */
};
static const ProtobufCIntRange event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Event",
  "Event",
  "Event",
  "",
  sizeof(Event),
  9,
  event__field_descriptors,
  event__field_indices_by_name,
  1,  event__number_ranges,
  (ProtobufCMessageInit) event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trace_data__stack_frames_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TraceData__StackFramesEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TraceData__StackFramesEntry, value),
    &stack_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trace_data__stack_frames_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange trace_data__stack_frames_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor trace_data__stack_frames_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TraceData.StackFramesEntry",
  "StackFramesEntry",
  "TraceData__StackFramesEntry",
  "",
  sizeof(TraceData__StackFramesEntry),
  2,
  trace_data__stack_frames_entry__field_descriptors,
  trace_data__stack_frames_entry__field_indices_by_name,
  1,  trace_data__stack_frames_entry__number_ranges,
  (ProtobufCMessageInit) trace_data__stack_frames_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trace_data__field_descriptors[3] =
{
  {
    "trace_events",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TraceData, n_trace_events),
    offsetof(TraceData, trace_events),
    &event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stack_frames",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TraceData, n_stack_frames),
    offsetof(TraceData, stack_frames),
    &trace_data__stack_frames_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "samples",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(TraceData, n_samples),
    offsetof(TraceData, samples),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trace_data__field_indices_by_name[] = {
  2,   /* field[2] = samples */
  1,   /* field[1] = stack_frames */
  0,   /* field[0] = trace_events */
};
static const ProtobufCIntRange trace_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor trace_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TraceData",
  "TraceData",
  "TraceData",
  "",
  sizeof(TraceData),
  3,
  trace_data__field_descriptors,
  trace_data__field_indices_by_name,
  1,  trace_data__number_ranges,
  (ProtobufCMessageInit) trace_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
