# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pytorch.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'pytorch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpytorch.proto\".\n\nStackFrame\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x04\x12\x0f\n\x07so_name\x18\x02 \x01(\t\"\xb2\x01\n\x0cPytorchStage\x12\x10\n\x08stage_id\x18\x01 \x01(\r\x12\x1e\n\nstage_type\x18\x02 \x01(\x0e\x32\n.StageType\x12\x0c\n\x04rank\x18\x03 \x01(\r\x12\x0f\n\x07step_id\x18\x04 \x01(\r\x12\x0c\n\x04\x63omm\x18\x05 \x01(\t\x12\x10\n\x08start_us\x18\x06 \x01(\x04\x12\x0e\n\x06\x65nd_us\x18\x07 \x01(\x04\x12!\n\x0cstack_frames\x18\x08 \x03(\x0b\x32\x0b.StackFrame\"0\n\x07Pytorch\x12%\n\x0epytorch_stages\x18\x01 \x03(\x0b\x32\r.PytorchStage*H\n\tStageType\x12\x14\n\x10STAGE_DATALOADER\x10\x00\x12\x11\n\rSTAGE_FORWARD\x10\x01\x12\x12\n\x0eSTAGE_BACKWARD\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pytorch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STAGETYPE']._serialized_start=296
  _globals['_STAGETYPE']._serialized_end=368
  _globals['_STACKFRAME']._serialized_start=17
  _globals['_STACKFRAME']._serialized_end=63
  _globals['_PYTORCHSTAGE']._serialized_start=66
  _globals['_PYTORCHSTAGE']._serialized_end=244
  _globals['_PYTORCH']._serialized_start=246
  _globals['_PYTORCH']._serialized_end=294
# @@protoc_insertion_point(module_scope)
